title: 'Designing Interfaces, Building Experiences.'
description: I've worked on a variety of projects...
redirectButtons:
  - link: mailto:your.email@example.com
    text: Email me
    color: primary
